spring:
  application:
    name: ecommerce
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
jwt:
  secret: ${SECRET_JWT}
  expiration: ${JWT_EXPIRED_TIME:3600}
  token-prefix: Bearer
  header: Authorization

grpc:
  client:
    vector-service:
      address: localhost # Or the actual host of your gRPC server
      port: 50051      # Or the actual port of your gRPC server
